name: Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli

    steps:
    - uses: actions/checkout@v3
      with:
        repo: qmk/qmk_firmware
        path: qmk

    - uses: actions/checkout@v3
      with:
        path: qmk/keyboards/crkbd/keymaps/alphadel

    - name: Run Build
      run: make -C qmk crkbd/rev1:alphadel

    - name: Upload uberjar artifact
      uses: actions/upload-artifact@v3
      with:
        name: hex-firwmare
        path: ~/qmk/crkbd_alphadel.hex
        retention-days: 1
